[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools==80.9.0"]

[dependency-groups]
dev = [
    {include-group="freeze"},
    {include-group="tests"},
    {include-group="lint"},
]
freeze = [
    "pyinstaller==6.19.0",
]
tests = [
    "pytest==9.0.2",
    "pytest-cov==7.1.0",
]
lint = [
    "pylint",
    "vulture",
    "ruff",
]

[project]
name = "sacamantecas"
dynamic = ["version"]
description = "Saca las mantecas…"
readme = "README.md"
requires-python = ">= 3.14"
license = "MIT"
license-files = ["LICENSE"]
authors = [{name="Raúl Núñez de Arenas Coronado", email="raulnac@gmail.com"}]
maintainers = [{name="Raúl Núñez de Arenas Coronado", email="raulnac@gmail.com"}]
dependencies = [
    "legion @ git+https://github.com/DervishD/legion.git@v3.0.5",
    "openpyxl==3.1.5",
]

[project.urls]
homepage = "https://github.com/DervishD/sacamantecas"
source = "https://github.com/DervishD/sacamantecas"
issues = "https://github.com/DervishD/sacamantecas/issues"

[tool.sacamantecas]
package_root = "src/{project[name]}"
version = "!!{version[release]!r} or '{version[tag]}.post0'"
build = "!!{version[release]!r} or '{version[tag]}.post{version[distance]}+{version[branch]}{version[detached]}.{version[rev]}{version[dirty]}'"
venv_path = "{project_root}/.venv"
build_path = "{project_root}/build"
main_script = "{local[package_root]}/__main__.py"
unpinned_deps = "!![__import__('re').split(r'[><=!@]', pkg)[0].strip().lower() for pkg in {project[dependencies]!r}]"
bundle_assets = [
    "{local[package_root]}/{project[name]}.ini",
    "{project_root}/CHANGELOG.md",
    "{project_root}/{project[readme]}",
]
colophon.path = "{local[package_root]}/about.py"
colophon.template = '''
    """Autogenerated, do not edit."""

    # pylint: disable=unused-variable
    PROGRAM_NAME = {project[name]!r}
    VERSION = {local[version]!r}
    BUILD = {local[build]!r}
    REPOSITORY = {project[urls][source]!r}
    DEPENDENCIES = {project[dependencies]!r}
'''

[tool.setuptools.dynamic]
version = {attr = "sacamantecas.about.BUILD"}

[tool.pytest]
pythonpath = ["src"]

[tool.ruff]
line-length = 120
target-version = "py314"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D203", "D213"]

[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*.py" = ["S101"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
order-by-type = false

[tool.pylint.main]
init-hook = "import sys, os; sys.path.insert(0, os.path.abspath('src'))"
persistent = false
jobs = 0
max-line-length = 120
enable = "all"
disable = ["I", "too-many-lines", "too-few-public-methods"]
allow-global-unused-variables = false

[tool.coverage.run]
branch = true
omit = [
    "build.py"
]

[tool.coverage.report]
show_missing = true
skip_empty = true
precision = 2
