#!/bin/sh
. "$(dirname "$0")/common"

VERSION=$(python tools/pluck.py local.version) || die 'Failed to get project version'
BUILD=$(python tools/pluck.py local.build) || die 'Failed to get project build code'

[ "$VERSION" = "$BUILD" ] && git tag -af "v$VERSION" -m ''
