"""Autogenerated, do not edit."""
# 2026-04-28 08:08:35

# pylint: disable=unused-variable
PROGRAM_NAME = 'sacamantecas'
VERSION = '5.4.0.post105+development.c2f37c7.dirty'
REPOSITORY = 'https://github.com/DervishD/sacamantecas'
DEPENDENCIES = ['legion @ git+https://github.com/DervishD/legion.git@development', 'openpyxl==3.1.3']
