"""Autogenerated, do not edit."""
# !!timestamp('%Y-%m-%d %H:%M:%S')

# pylint: disable=unused-variable
PROGRAM_NAME = 'sacamantecas'
VERSION = '5.4.0.post107+development.fb4cc47.dirty'
REPOSITORY = 'https://github.com/DervishD/sacamantecas'
DEPENDENCIES = ['legion @ git+https://github.com/DervishD/legion.git@development', 'openpyxl==3.1.3']
