"""Generate project metadata and dump it to `about.py`."""  # noqa: INP001
import contextlib
from pathlib import Path
import sys
from textwrap import dedent
import tomllib
from typing import Any

from legion import run

BRANCH_NAME_FOR_DETACHED_HEAD = 'DETACHED.HEAD'


def get_project_root() -> Path | None:
    """Get the root directory for current project."""
    project_root = None
    if not (result := run(['git', 'rev-parse', '--show-toplevel'], encoding='utf-8')).returncode:
        project_root = Path(result.stdout.strip())
    return project_root


def get_package_metadata(project_root: Path) -> dict[str, Any] | None:
    """Get the package metadata from `pyproject.toml`."""
    pyproject_toml_path = project_root / 'pyproject.toml'
    with contextlib.suppress(PermissionError, FileNotFoundError, tomllib.TOMLDecodeError):
        return tomllib.loads(pyproject_toml_path.read_text(encoding='utf-8'))
    return None


def get_version() -> str | None:
    """Get version for current project from `git` tags."""
    dirty_marker = 'dirty'
    if (result := run(['git', 'describe', '--long', f'--dirty=-{dirty_marker}'])).returncode:
        return None

    components = result.stdout.strip().split('-')

    dirty = components[-1] == dirty_marker
    tag, distance, rev = components[0:3]

    branch = BRANCH_NAME_FOR_DETACHED_HEAD
    if not (result := run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'])).returncode:
        branch = f'{result.stdout.strip()}'

    version = tag.removeprefix('v')
    if distance:
        version += f'.post{distance}+{branch}.{rev.removeprefix('g')}{f'.{dirty_marker}' if dirty else ''}'

    return version


STATUS_SUCCESS = 0
STATUS_FAILURE = 1
def main() -> int:
    """."""
    if (project_root := get_project_root()) is None:
        return STATUS_FAILURE

    if (package_metadata := get_package_metadata(project_root)) is None:
        return STATUS_FAILURE

    if (version := get_version()) is None:
        return STATUS_FAILURE

    name = package_metadata['project']['name']
    about_contents = dedent(f'''
        """Auto generated by `{Path(__file__).name}` for package `{name}` - do not edit."""

        PROGRAM_NAME = '{name}'
        VERSION = '{version}'
        REPOSITORY = '{package_metadata['project']['urls']['source']}'
        DEPENDENCIES = [{', '.join([f"'{dependency}'" for dependency in package_metadata['project']['dependencies']])}]
    ''').lstrip()

    about_path = Path(package_metadata['tool']['local']['sources_root']).resolve() / name/ 'about.py'
    with contextlib.suppress(PermissionError, FileNotFoundError):
        about_path.write_text(about_contents, encoding='utf-8')
        return STATUS_SUCCESS

    return STATUS_FAILURE


if __name__ == '__main__':
    sys.exit(main())
