"""Building script.

Build program executable for `Win32` in a virtual environment and pack
it, together with the corresponding `.ini` file and other assets, in a
`.zip` bundle for distribution.
"""  # noqa: INP001
import contextlib
import os
from pathlib import Path
import shutil
from subprocess import CalledProcessError, CompletedProcess
import sys
from typing import TYPE_CHECKING
from zipfile import ZIP_DEFLATED, ZipFile

from legion import ensure_utf8_output, get_project_metadata, run

if TYPE_CHECKING:
    from collections.abc import Iterable, Sequence
    from typing import TextIO


ERROR_MARKER = '\n*** '
ERROR_HEADER = 'Error, '
PROGRESS_MARKER = '  ▶ '


def pretty_print(message: str, *, marker: str = '', header: str = '', stream: TextIO = sys.stdout) -> None:
    """Pretty-print *message* to *stream*, with a final newline.

    The first line of the output will contain the *marker* and *header*,
    which are empty strings by default. All the subsequent lines will be
    indented with the length of the *marker* so they appear aligned with
    the *header*.

    The *stream* (`sys.stdout` by default) is finally flushed to ensure
    the message is printed.
    """
    marker_len = len([char for char in marker if char.isprintable()])

    lines = message.splitlines() if message else ['']
    lines[0] = f'{marker}{header}{lines[0]}'
    lines[1:] = [f'\n{' ' * marker_len}{line}' for line in lines[1:]]
    lines[-1] += '\n'
    stream.writelines(lines)
    stream.flush()


def error(message: str) -> None:
    """Pretty-print error message to `sys.stderr`."""
    pretty_print(message, marker=ERROR_MARKER, header=ERROR_HEADER, stream=sys.stderr)


def progress(message: str) -> None:
    """Pretty-print progress message to `sys.stdout`."""
    pretty_print(message, marker=PROGRESS_MARKER)


def run_command(command: Sequence[str]) -> CompletedProcess[str]:
    """Run *command*, capturing its output."""
    try:
        return run(command, check=True, encoding='utf-8')
    except FileNotFoundError as exc:
        raise CalledProcessError(0, command, None, f"Command '{command[0]}' not found.\n") from exc


def is_venv_ready(venv_path: Path) -> bool:
    """Check if the virtual environment is active and functional."""
    # If no virtual environment exists, try to use global packages.
    if not venv_path.exists():
        return True

    # But if it exists, it has to be active.
    if os.environ.get('VIRTUAL_ENV', '').lower() != str(venv_path).lower():
        error('wrong or missing VIRTUAL_ENV environment variable.')
        return False

    if sys.prefix == sys.base_prefix:
        error('virtual environment is not active.')
        return False

    return True


def are_required_packages_installed(required: list[str]) -> bool:
    """Check that *required_packages* are installed."""
    pip_list = ['pip', 'list', '--local', '--format=freeze', '--not-required', '--exclude=pip', '--exclude-editable']
    installed = {line.split('==', maxsplit=1)[0].lower() for line in run_command(pip_list).stdout.splitlines()}

    if diff := set(required) - installed:
        diff = '\n'.join(diff)
        error(f'missing packages:\n{diff}\n')
        return False

    return True


def prepare_build_directory(build_path: Path) -> bool:
    """Prepare the *build_path* build directory."""
    # Create the directory if it does not already exist.
    # Create the .gitignore file.
    # Remove current contents except .gitignore file.
    error_message = 'last build leftovers cannot be removed.'
    try:
        with contextlib.suppress(FileNotFoundError):
            shutil.rmtree(build_path)
        error_message = 'build directory cannot be created'
        build_path.mkdir()
        error_message = 'the .gitignore file cannot be created'
        (build_path / '.gitignore').write_text('# Autogenerated, do not edit.\n*\n', encoding='utf-8', newline='\n')
    except PermissionError:
        error(error_message)
        return False
    return True


def build_frozen_executable(script_path: Path, frozen_exe_path: Path) -> bool:
    """Build *frozen_exe_path* from *script_path*."""
    build_path = frozen_exe_path.parent

    if frozen_exe_path.exists():
        frozen_exe_path.unlink()

    cmd = ['pyinstaller']
    cmd.append('--log-level=WARN')
    cmd.extend([f'--workpath={build_path}', f'--specpath={build_path}', f'--distpath={build_path}'])
    cmd.extend(['--onefile', '--name', frozen_exe_path.stem])
    cmd.append(str(script_path))
    try:
        run_command(cmd)
    except CalledProcessError as exc:
        error(f'could not create frozen executable.\n{exc.stderr}')
        return False

    return True


def create_bundle(bundle_path: Path, manifest:Iterable[Path]) -> None:
    """Build bundle at *bundle_path* containing *manifest* paths."""
    with ZipFile(bundle_path, 'w', compression=ZIP_DEFLATED, compresslevel=9) as bundle:
        for path in manifest:
            bundle.write(path, path.name)


@ensure_utf8_output
def main() -> int:
    """."""
    if (metadata := get_project_metadata()) is None:
        error('project metadata not found, build aborted.')
        return 1

    program_name = metadata['project']['name']
    program_version = metadata['local']['build'].split('+', maxsplit=1)[0]
    pretty_print(f'Building {program_name} v{program_version}')

    venv_path = Path(metadata['local']['venv_path'])
    progress(f'Checking virtual environment: {venv_path}')
    if not is_venv_ready(venv_path):
        return 1

    required_packages = metadata['local']['unpinned_deps']
    progress(f'Checking that required packages are installed: {', '.join(required_packages)}')
    if not are_required_packages_installed(required_packages):
        return 1

    build_path = Path(metadata['local']['build_path'])
    progress(f'Preparing build directory: {build_path}')
    if not prepare_build_directory(build_path):
        return 1

    frozen_exe_path = (build_path / program_name).with_suffix('.exe')
    progress(f'Building frozen executable: {frozen_exe_path}')
    if not build_frozen_executable(metadata['local']['main_script'], frozen_exe_path):
        return 1

    bundle_path = Path(metadata['project_root']) / f'{program_name}_v{program_version}.zip'
    manifest = (frozen_exe_path, *[Path(asset) for asset in metadata['local']['bundle_assets']])
    progress(f'Building distributable bundle: {bundle_path}')
    create_bundle(bundle_path, manifest)

    pretty_print('\nApplication built successfully!')

    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(1)
