"""Generate project metadata and dump it to `about.py`."""  # noqa: INP001
import contextlib
from pathlib import Path
import re
import sys
from textwrap import dedent

from legion import excepthook, git_repository_root, load_pyproject, run

BRANCH_NAME_FOR_DETACHED_HEAD = '<detached head>'
BRANCH_NAME_ESCAPE_SEQUENCE = 'xxx'


def get_version() -> str | None:
    """Get version for current project from `git` tags."""
    dirty_marker = 'dirty'
    if (result := run(['git', 'describe', '--long', f'--dirty=-{dirty_marker}'])).returncode:
        return None

    components = result.stdout.strip().split('-')

    dirty = components[-1] == dirty_marker
    tag, distance, rev = components[0:3]

    branch = BRANCH_NAME_FOR_DETACHED_HEAD
    if not (result := run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'])).returncode:
        branch = f'{result.stdout.strip()}'

    branch = re.sub(r'[^a-z0-9]', BRANCH_NAME_ESCAPE_SEQUENCE, branch.lower())

    version = tag.removeprefix('v')
    if distance:
        version += f'.post{distance}+{branch}.{rev.removeprefix('g')}{f'.{dirty_marker}' if dirty else ''}'

    return version


STATUS_SUCCESS = 0
STATUS_FAILURE = 1
def main() -> int:
    """."""
    sys.excepthook = excepthook

    if (project_root := git_repository_root()) is None:
        return STATUS_FAILURE

    if (package_metadata := load_pyproject(project_root)) is None:
        return STATUS_FAILURE

    if (version := get_version()) is None:
        return STATUS_FAILURE

    name = package_metadata['project']['name']
    about_contents = dedent(f'''
        """Auto generated by `{Path(__file__).name}` for package `{name}` - do not edit."""

        # pylint: disable=unused-variable
        PROGRAM_NAME = '{name}'
        VERSION = '{version}'
        REPOSITORY = '{package_metadata['project']['urls']['source']}'
        DEPENDENCIES = [{', '.join([f"'{dependency}'" for dependency in package_metadata['project']['dependencies']])}]
    ''').lstrip()

    about_path = project_root / 'src' / name / 'about.py'
    with contextlib.suppress(PermissionError, FileNotFoundError):
        about_path.write_text(about_contents, encoding='utf-8')
        return STATUS_SUCCESS

    return STATUS_FAILURE


if __name__ == '__main__':
    sys.exit(main())
